In [2]:
import numpy as np

# creating Array from Python object

In [3]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


# creating the mulltidimensional arrays

In [4]:
matrix=np.array([[1,2,3],
               [4,5,6]])

In [5]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [6]:
print(matrix.ndim) # print the dimension of  array

2


In [7]:
matrix1=np.array([  [1,2,3],
                    [4,5,6],
                    [7,8,9]
                 ])

# initializing with zeros

In [8]:
z=np.zeros((2,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


# initializing with ones

In [9]:
one=np.ones((3,2))

In [10]:
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


# for the range of values

In [11]:
r=np.arange(0,10,2)
print(r)

[0 2 4 6 8]


In [12]:
new_r=np.arange(3,30,4)
print(new_r)

[ 3  7 11 15 19 23 27]


# Evenly Spaced Values

In [13]:
l=np.linspace(0,1,5)
print(l)

[0.   0.25 0.5  0.75 1.  ]


In [14]:
l1=np.linspace(2,4,5)
print(l1)

[2.  2.5 3.  3.5 4. ]


# dtype

In [15]:
arr=np.array([1,2,3],dtype=np.float32)
print(arr)

[1. 2. 3.]


# 2) Array Attributes

In [16]:
arr1=np.array([[1,2,3],[4,5,6]])


In [17]:
print('Shape',arr1.shape)

Shape (2, 3)


In [18]:
print('Size',arr1.size)

Size 6


In [19]:
print('Dimension',arr1.ndim)

Dimension 2


In [20]:
print('Data Type',arr1.dtype)

Data Type int64


In [21]:
print(arr1.itemsize) # memory used by the one element

8


In [22]:
print(arr1.nbytes) # total memory used ie nbytes=size*itemsize

48


# 3) Indexing and Slicing 

In [23]:
print(arr1[0]) # printing the first element that is first row

[1 2 3]


In [24]:
print(arr1[-1]) # printing the last element that is last row

[4 5 6]


In [25]:
print(arr1[0][1]) # printing the second element inside the first element

2


In [26]:
ar=np.array([10,20,30,40,50,60])

In [27]:
print(ar[1:3])

[20 30]


In [28]:
print(ar[:4])

[10 20 30 40]


In [29]:
print(ar[::3]) # step slicing with the step 3

[10 40]


# slicing in 2D arrays

In [30]:
print(arr1[0])

[1 2 3]


In [31]:
print(arr1[:,1]) # print all the row but only the second column

[2 5]


In [32]:
print(arr1[:,0]) # print all the row but only the first column

[1 4]


In [33]:
print(arr1[0,1])

2


In [36]:
# fancy indexing
print(ar[[1,3]])

[20 40]


In [39]:
# boolean indexing 
print(ar[ar>25])

[30 40 50 60]


# 4) Array Operations

In [48]:
c=np.array([6,8,10])
d=np.array([3,4,5])

In [49]:
print(c+d)
print(c-d) 
print(c*d) 
print(c/d)

[ 9 12 15]
[3 4 5]
[18 32 50]
[2. 2. 2.]


In [50]:
# operations with scalars
print(c+2)
print(c*2)

[ 8 10 12]
[12 16 20]
